name: library_name_example
description: Example application for library_name.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  library_name:
    path: ..

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
